name: Test Complex Composite Action

on:
  push:
    branches:
      - main

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Complex Composite Action
        uses: mohitmsingh/my-composite-action@main
        with:
          greeting: 'Hi'
          filename: 'test-file.txt'
          timestamp_format: "%Y-%m-%d %H:%M:%S"
